permalink: /blog/:year/:month/:day/:title.html
title: screenshot-tests-for-android
tagline:  Generate fast deterministic screenshots while running instrumentation tests in android.
fbappid: ""
gacode: "myproject-google-analytics-code"
description:
baseurl: /screenshot-tests-for-android/
url: https://facebook.github.io
ghrepo: "facebook/screenshot-tests-for-android"

# Build settings
markdown: redcarpet
highlighter: pygments
lsi: false

exclude: [README.md, Gemfile, scripts, vendor]
keep_files: [.git, .hg]

collections:
  docs:
    output: true
    permalink: /docs/:name/

sass:
  style: :compressed

redcarpet:
  extensions: [with_toc_data, no_intra_emphasis, tables, autolink]

color:
  # Provides colour for background of top header of homepage
  primary: "#6779ff"
  # Provides colour for background of elsewhere on site
  secondary: "#e4e4e4"
  # A color that will work for buttons laid on top of primary colour
  light: "#4356e6"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#151515"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#4356e6"
  # Text of links in the nav
  navtext: "#bfc6ff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#4356e6"
